Server_Side_Scripting/ruby/Program_2/Book Application/config/routes.rb
Rails.application.routes.draw do
  resources :book_details
  get "up" => "rails/health#show", as: :rails_health_check
   root "book_details#index"
end

Server_Side_Scripting/ruby/Program_2/Book Application/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

Server_Side_Scripting/ruby/Program_2/Book Application/app/models/book_detail.rb
class BookDetail < ApplicationRecord
end

Server_Side_Scripting/ruby/Program_2/Book Application/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Server_Side_Scripting/ruby/Program_2/Book Application/app/controllers/book_details_controller.rb
class BookDetailsController < ApplicationController
  before_action :set_book_detail, only: %i[ show edit update destroy ]

  # GET /book_details or /book_details.json
  def index
    @book_details = BookDetail.all
  end

  # GET /book_details/1 or /book_details/1.json
  def show
  end

  # GET /book_details/new
  def new
    @book_detail = BookDetail.new
  end

  # GET /book_details/1/edit
  def edit
  end

  # POST /book_details or /book_details.json
  def create
    @book_detail = BookDetail.new(book_detail_params)

    respond_to do |format|
      if @book_detail.save
        format.html { redirect_to book_detail_url(@book_detail), notice: "Book detail was successfully created." }
        format.json { render :show, status: :created, location: @book_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_details/1 or /book_details/1.json
  def update
    respond_to do |format|
      if @book_detail.update(book_detail_params)
        format.html { redirect_to book_detail_url(@book_detail), notice: "Book detail was successfully updated." }
        format.json { render :show, status: :ok, location: @book_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_details/1 or /book_details/1.json
  def destroy
    @book_detail.destroy!

    respond_to do |format|
      format.html { redirect_to book_details_url, notice: "Book detail was successfully delete." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_detail
      @book_detail = BookDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_detail_params
      params.require(:book_detail).permit(:Book_Name, :Author, :Price, :Mail_ID)
    end
end

Server_Side_Scripting/ruby/Program_2/Book Application/app/helpers/application_helper.rb
module ApplicationHelper
end

Server_Side_Scripting/ruby/Program_2/Book Application/app/helpers/book_details_helper.rb
module BookDetailsHelper
end

Server_Side_Scripting/ruby/Program_2/Book Application/app/views/book_details/_book_detail.html.erb
<div id="<%= dom_id book_detail %>">
  <p>
    <strong>Book name:</strong>
    <%= book_detail.Book_Name %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book_detail.Author %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= book_detail.Price %>
  </p>

  <p>
    <strong>Mail id:</strong>
    <%= book_detail.Mail_ID %>
  </p>

</div>

Server_Side_Scripting/ruby/Program_2/Book Application/app/views/book_details/_form.html.erb
<%= form_with(model: book_detail) do |form| %>
  <% if book_detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book_detail.errors.count, "error") %> prohibited this book_detail from being saved:</h2>

      <ul>
        <% book_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Book_Name, style: "display: block" %>
    <%= form.text_field :Book_Name %>
  </div>

  <div>
    <%= form.label :Author, style: "display: block" %>
    <%= form.text_field :Author %>
  </div>

  <div>
    <%= form.label :Price, style: "display: block" %>
    <%= form.text_field :Price %>
  </div>

  <div>
    <%= form.label :Mail_ID, style: "display: block" %>
    <%= form.text_field :Mail_ID %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

Server_Side_Scripting/ruby/Program_2/Book Application/app/views/book_details/edit.html.erb
<h1>Edit</h1>

<%= render "form", book_detail: @book_detail %>

<br>

<div>
  <%= link_to "Show", @book_detail %> |
  <%= link_to "Back", book_details_path %>
</div>

Server_Side_Scripting/ruby/Program_2/Book Application/app/views/book_details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Book details</h1>

<div id="book_details">
  <% @book_details.each do |book_detail| %>
    <%= render book_detail %>
    <p>
      <%= link_to "Show", book_detail %>
    </p>
  <% end %>
</div>

<%= link_to "New", new_book_detail_path %>

Server_Side_Scripting/ruby/Program_2/Book Application/app/views/book_details/new.html.erb
<h1>New book detail</h1>

<%= render "form", book_detail: @book_detail %>

<br>

<div>
  <%= link_to "Back", book_details_path %>
</div>

Server_Side_Scripting/ruby/Program_2/Book Application/app/views/book_details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @book_detail %>

<div>
  <%= link_to "Edit", edit_book_detail_path(@book_detail) %> |
  <%= link_to "Back", book_details_path %>

  <%= button_to "Delete", @book_detail, method: :delete %>
</div>

Server_Side_Scripting/ruby/Program_2/Book Application/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>